services:
  - type: web
    name: modmail-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: MODMAIL_CATEGORY_ID
        sync: false
      - key: STAFF_ROLE_ID
        sync: false
